### ISSUE TITLE
linux setup-sdl failing in CI 

### ISSUE THREAD

**Issue by sezero** [libsdl-org/sdl2-compat#237]
Happened in my fork, and upon a re-run too:
https://github.com/sezero/sdl2-compat/actions/runs/12333314225/job/34422370637

CC @madebr

**Comment by sezero** [comment]
Excerpt from failure log, if it helps:

```
node:internal/errors:984
  const err = new Error(message);
              ^

Error: Command failed: "cmake" "-S" "/tmp/setupsdl/936faf9b486d2336e1d4a1813bae448f3382ce58e76f2011fdda7cdb5a587c59/source" "-B" "/tmp/setupsdl/936faf9b486d2336e1d4a1813bae448f3382ce58e76f2011fdda7cdb5a587c59/build" "-DSDL_VENDOR_INFO="libsdl-org/setup-sdl"" "-DSDL_CMAKE_DEBUG_POSTFIX=" "-DSDL_TEST_LIBRARY=true" "-DCMAKE_BUILD_TYPE=Debug" "-DCMAKE_INSTALL_BINDIR=bin" "-DCMAKE_INSTALL_INCLUDEDIR=include" "-DCMAKE_INSTALL_LIBDIR=lib" "-G" ""Ninja"" "-DCMAKE_INSTALL_PREFIX=/tmp/setupsdl/936faf9b486d2336e1d4a1813bae448f3382ce58e76f2011fdda7cdb5a587c59/package"
    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at checkExecSyncError (node:child_process:891:11)
    at Object.execSync (node:child_process:963:15)
    at __webpack_modules__.9538.Executor.run (/home/runner/work/_actions/libsdl-org/setup-sdl/main/packed/index.js:226:23)
    at /home/runner/work/_actions/libsdl-org/setup-sdl/main/packed/index.js:273:47
    at step (/home/runner/work/_actions/libsdl-org/setup-sdl/main/packed/index.js:63:23)
    at Object.next (/home/runner/work/_actions/libsdl-org/setup-sdl/main/packed/index.js:44:53)
    at /home/runner/work/_actions/libsdl-org/setup-sdl/main/packed/index.js:38:71
    at new Promise (<anonymous>) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 1902,
  stdout: null,
  stderr: null
}

Node.js v20.18.0
```

**Comment by madebr** [comment]
I think we need to add `-DSDL_UNIX_CONSOLE_BUILD=ON` as a default CMake argument in setup-sdl.
https://github.com/libsdl-org/SDL/blob/main/docs/README-cmake.md#cmake-fails-to-build-without-x11-or-wayland-support

**Comment by madebr** [comment]
@sezero  Can you retry?

**Comment by sezero** [comment]
> @sezero Can you retry?

Works now, thanks
